unpackaged/main/default/objects/Communications_Content__c/Communications_Content__c.object-meta.xml
<CustomObject>
    <label>Communications Content</label>
    <nameField>
        <displayFormat>CC-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communications Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Communications_Content__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Content</fullName>
            </value>
            <value>
                <fullName>In-Store Events</fullName>
            </value>
            <value>
                <fullName>Recruitment &amp; Employment</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Promotional Offers</fullName>
            </value>
            <value>
                <fullName>Inventory Updates</fullName>
            </value>
            <value>
                <fullName>WorkWell</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Communications_Content__c/fields/Parent_Comm_Content__c.field-meta.xml
<CustomField>
    <fullName>Parent_Comm_Content__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Comm Content</label>
    <referenceTo>Communications_Content__c</referenceTo>
    <relationshipLabel>Child Communications Content</relationshipLabel>
    <relationshipName>Communications_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/cPortal_ContentHierarchyCmpController.cls
/**
 * @description       : 
 * @author            : Manoj_Goswami
 * @group             : 
 * @last modified on  : 2023-02-23
 * @last modified by  : Manoj_Goswami
**/
public with sharing class cPortal_ContentHierarchyCmpController {
    @AuraEnabled(cacheable=true)
    public static List<Communications_Content__c> findAllHierarchyCommunicationContent(string recordId){
        List<Communications_Content__c> allCommContentList = new List<Communications_Content__c>();
        String ultimateCommContentId;
        for(Communications_Content__c commContent : [SELECT Id, Parent_Comm_Content__c 
                                                     FROM Communications_Content__c 
                                                     WHERE Id=:recordId]){
                                                         ultimateCommContentId = commContent.Parent_Comm_Content__c;
                                                     }
        if(string.isNotBlank(ultimateCommContentId)){
            for(Communications_Content__c comm : [SELECT Id, (SELECT id FROM Communications_Content__r),
                                                 Name, Parent_Comm_Content__c, Category__c 
                                                 FROM Communications_Content__c 
                                                 WHERE Parent_Comm_Content__c=:ultimateCommContentId 
                                                 ORDER BY Parent_Comm_Content__c NULLS FIRST]){
                                                     allCommContentList.add(comm);
                                                 }
        }
        system.debug('***allCommContentList size:'+allCommContentList);
        return allCommContentList;
    }
}